name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: lily58_left nice_view_adapter nice_view
          - board: nice_nano_v2
            shield: lily58_right nice_view_adapter nice_view
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache west modules
        uses: actions/cache@v3
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-modules-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD="${{ matrix.shield }}" -DZMK_CONFIG=/config
      - name: Rename artifacts
        run: |
          mkdir artifacts
          for file in build/zephyr/zmk.uf2 build/zephyr/zmk.hex; do
            if [ -f "$file" ]; then
              cp "$file" "artifacts/$(basename $file | cut -d. -f1)-${{ matrix.board }}-${{ matrix.shield }}-$(date +"%Y%m%d%H%M%S").${file##*.}"
            fi
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: artifacts
