# Uncomment the following line to enable deep sleep
# CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable eager debouncing

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
# Enable display support

CONFIG_ZMK_DISPLAY=y

# Enable a built-in status screen (use custom screen if needed, but no changes here)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

# Enable split keyboard and BLE support
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Increase Bluetooth power and connection parameters
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Bluetooth settings
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5